// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWiTPVYCQ1Lo9u0zqK_7norbpVh6AfXts',
    appId: '1:602412055006:web:96f5b98cdf5cd2d872054f',
    messagingSenderId: '602412055006',
    projectId: 'skillconnect-ec581',
    authDomain: 'skillconnect-ec581.firebaseapp.com',
    storageBucket: 'skillconnect-ec581.firebasestorage.app',
    measurementId: 'G-2B63PJH02X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjgMv5kt-VupGgndr5gp9Mgvi29iJGxpM',
    appId: '1:602412055006:android:5cd333d9de5ef50672054f',
    messagingSenderId: '602412055006',
    projectId: 'skillconnect-ec581',
    storageBucket: 'skillconnect-ec581.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBepOpDfFup9biZ-8agBQK3KRgHRusA-Bk',
    appId: '1:602412055006:ios:83bcb7b828d60fbb72054f',
    messagingSenderId: '602412055006',
    projectId: 'skillconnect-ec581',
    storageBucket: 'skillconnect-ec581.firebasestorage.app',
    iosClientId:
        '602412055006-r00gp9di30e6irvneorh50agf76i8560.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBepOpDfFup9biZ-8agBQK3KRgHRusA-Bk',
    appId: '1:602412055006:ios:83bcb7b828d60fbb72054f',
    messagingSenderId: '602412055006',
    projectId: 'skillconnect-ec581',
    storageBucket: 'skillconnect-ec581.firebasestorage.app',
    iosClientId:
        '602412055006-r00gp9di30e6irvneorh50agf76i8560.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWiTPVYCQ1Lo9u0zqK_7norbpVh6AfXts',
    appId: '1:602412055006:web:f564292f6c4ec71472054f',
    messagingSenderId: '602412055006',
    projectId: 'skillconnect-ec581',
    authDomain: 'skillconnect-ec581.firebaseapp.com',
    storageBucket: 'skillconnect-ec581.firebasestorage.app',
    measurementId: 'G-8LTQTKR8Y5',
  );
}
